default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: enab_dev
  host: localhost

test:
  <<: *default
  database: enab_test
  host: localhost

production:
  <<: *default
  database: enab
  username: enab_app

